[package]
name = "marsh"
version = "0.1.0"
authors = ["Torrencem <matt@torrencefamily.net>"]
edition = "2018"

[build-dependencies]
lalrpop = { version="0.18.1", features=["lexer"] }

[dependencies]
lalrpop-util = "0.18.1"

clap = "2.33.0"
